global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'politicians-profile'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['politicians-profile:8080']
  - job_name: 'grafana'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']