version: '3.8'
services:
  elastic-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411