version: '3.8'
services:
  politicians-profile:
    image: simi/politicians-profile
    ports:
      - 8080:8080
    labels:
      collect_logs: "true"
      decode_logs_to_json: "true"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.2
    volumes:
      - ./filebeat/filebeat.docker.yaml:/containers/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: on-failure
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./containers/prometheus:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./containers/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus