version: '3.8'
services:
  politicians-profile:
    image: simi/politicians-profile
    ports:
      - 8080:8080
    labels:
      collect_logs: "true"
      decode_logs_to_json: "true"
    depends_on:
      - jaeger-server
    networks:
      - docker-network
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
    networks:
      - docker-network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
    networks:
      - docker-network
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.9.2
    volumes:
      - ./filebeat/filebeat.docker.yaml:/containers/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: on-failure
    networks:
      - docker-network
  jaeger-server:
    image: jaegertracing/all-in-one:1.19
    container_name: "jaeger-server"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411
    networks:
      - docker-network
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./containers/prometheus:/prometheus
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    networks:
      - docker-network
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./containers/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge